# Generated by Django 3.2 on 2021-04-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0006_auto_20210210_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total',
            field=models.DecimalField(decimal_places=4, max_digits=9),
        ),
    ]
