# Generated by Django 3.2 on 2021-04-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0007_alter_wallet_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capital',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
