# Generated by Django 3.2 on 2021-04-12 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0008_profile_capital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('daily', models.PositiveIntegerField()),
                ('weekly', models.PositiveIntegerField()),
                ('monthly', models.PositiveIntegerField()),
                ('annually', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='cap.profile')),
            ],
        ),
    ]
