# Generated by Django 3.2 on 2021-04-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0010_plans_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='profile',
        ),
        migrations.AddField(
            model_name='plans',
            name='profile',
            field=models.ManyToManyField(related_name='plans', to='cap.Profile'),
        ),
    ]
