# Generated by Django 3.2 on 2021-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0012_alter_plans_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='period',
            field=models.TextField(default='1year'),
        ),
    ]
