# Generated by Django 3.2 on 2021-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0014_auto_20210501_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
