# Generated by Django 3.2 on 2021-05-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0015_auto_20210503_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dp',
        ),
        migrations.AlterField(
            model_name='profile',
            name='pot',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
