# Generated by Django 3.2 on 2021-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
    ]
