# Generated by Django 3.2 on 2021-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0018_profile_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=8, null=True),
        ),
    ]
